scripts/rails/blog_hacked/config/routes.rb
Blog::Application.routes.draw do
  	
  resources :contact_forms

  devise_for :authors

  resources :authors

  resources :posts do
	get :queue, :on => :collection
	resources :comments
  end
  
  match "/posts/:post_id/comments/:id" => "comments#destroy"
  
  root :to => "posts#index"
  

end

scripts/rails/blog_hacked/app/models/author.rb
class Author < ActiveRecord::Base	
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable  :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :age, :email, :password, :password_confirmation, :remember_me
	
	has_many :posts
	
	validates :name, :age, :presence => true

end

scripts/rails/blog_hacked/app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :post

end

scripts/rails/blog_hacked/app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name
  attribute :author_id
  attribute :message
  attribute :email
  
  validates :name, :email, :author_id, :message, :presence => true
  
  def headers
    { :to => Author.find(author_id).email }
  end
end

scripts/rails/blog_hacked/app/models/post.rb
class Post < ActiveRecord::Base
	
	belongs_to :author
	has_many   :comments
		
	scope :desc, order("published_on desc").includes(:author)
	scope :asc , order("published_on asc").includes(:author)
	
	validates_presence_of :tittle
	validates_presence_of :body
	
	def self.past
		where("published_on <= ?",Date.today).desc
	end
	
	def self.future
		where("published_on > ?",Date.today).asc
	end

end

scripts/rails/blog_hacked/app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

scripts/rails/blog_hacked/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :authenticate_author!, :except => [:index, :show]	

  # GET /authors
  # GET /authors.xml
  def index
    @authors = Author.all
    respond_with(@authors)
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    @author = Author.find(params[:id])
    respond_with(@author)
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new
    respond_with(@author)
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.xml
  def create
    @author = Author.new(params[:author])
    @author.save
    respond_with(@author)
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
    @author = Author.find(params[:id])
    @author.update_attributes(params[:author])
    respond_with(@author)
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    respond_with(@author)
  end
end

scripts/rails/blog_hacked/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_filter :authenticate_author!, :only => :destroy
	
	def create
		post = Post.find(params[:post_id])
		post.comments.create(params[:comment])
		redirect_to post
	end
	
	def destroy
	   post = Post.find(params[:post_id])
	   comment = Comment.find(params[:id])
	   comment.destroy
	   redirect_to post
	end
	
end

scripts/rails/blog_hacked/app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  
  # GET /contact_forms/new
  # GET /contact_forms/new.xml
  def new
    @contact_form = ContactForm.new
    respond_with(@contact_form)
  end

  # POST /contact_forms
  # POST /contact_forms.xml
  def create
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.deliver
		redirect_to root_path, :notice => "Thanks for your message"
	else 	
	   render "new"		
    end
  end
end

scripts/rails/blog_hacked/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :html, :atom, :only => [:index, :show]
	
	before_filter :authenticate_author!, :except => [:index, :show]
	before_filter :sweep_cache, :only => [:create,:update,:destroy]
	caches_action :index
	
	def index
		@posts = Post.past
		respond_with @posts
	end
	
	def queue
		@posts = Post.future
		respond_with @posts do |format|
			format.html { render "index" }
		end
	end
	
	def show
		@post = Post.find(params[:id])
		respond_with @post
	end
	
	def new
		@post = Post.new
	end
	
	def create
		@post = current_author.posts.build(params[:post])
		@post.save
		respond_with(@post) 
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(params[:id])
		@post.update_attributes(params[:post])
		respond_with(@post)
	end
	
	def destroy
	   @post = Post.find(params[:id])
	   @post.destroy
	   respond_with(@post)
	end
	
	private 
	
	def sweep_cache
		expire_action :action => :index
	end
	
end

scripts/rails/blog_hacked/app/helpers/authors_helper.rb
module AuthorsHelper
end

scripts/rails/blog_hacked/app/helpers/comments_helper.rb
module CommentsHelper
end

scripts/rails/blog_hacked/app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

scripts/rails/blog_hacked/app/helpers/posts_helper.rb
module PostsHelper
end

scripts/rails/blog_hacked/app/views/authors/_form.html.erb
<%= simple_form_for(@author) do |f| %>
  <%= f.error_messages %>

  <div class="inputs">
    <%= f.input :name %>
	<%= f.input :email %>
    <%= f.input :age %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

scripts/rails/blog_hacked/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

scripts/rails/blog_hacked/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.age %></td>
    <td><%= link_to 'Show', author %></td>
	<% if author_signed_in? %>
		<td><%= link_to 'Edit', edit_author_path(author) %></td>
		<td><%= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>		
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

scripts/rails/blog_hacked/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

scripts/rails/blog_hacked/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>

<p>
  <b>Age:</b>
  <%= @author.age %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

scripts/rails/blog_hacked/app/views/contact_forms/new.html.erb
<h1>Send an author message</h1>

<%= simple_form_for(@contact_form) do |f| %>
  <%= f.error_messages %>

  <div class="inputs">
    <%= f.input :name %>
	<%= f.input :email %>
    <%= f.input :author_id, :collection => Author.all %>
    <%= f.input :message, :as => :text %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Send" %>
  </div>
<% end %>


<%= link_to 'Back', contact_forms_path %>

scripts/rails/blog_hacked/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= auto_discovery_link_tag(:atom, posts_path(:atom)) %>
</head>
<body>

<div id="author_nav">
	<% if author_signed_in? %>
		Signed in as <b><%= current_author.name %></b>
	    <%= link_to "Edit", edit_author_path(current_author) %>	
	    <%= link_to "Sign out", destroy_author_session_path %>	
	<% else %>
		<%= link_to "Sign in", new_author_session_path %>	
    <% end %> 	
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

scripts/rails/blog_hacked/app/views/posts/_form.html.erb
<% form_for @post do |form|  %>
	<%= form.error_messages %>

	<%= form.text_field :tittle %><br/>
	<%= form.text_area  :body   %><br/>
	<label>Publish On</label>
	<%= form.date_select :published_on %> <br/>
	<%= form.submit %>
<% end %>

scripts/rails/blog_hacked/app/views/posts/edit.html.erb
<h1>Edit a new post </h1>
<%= render "form" %>

scripts/rails/blog_hacked/app/views/posts/index.html.erb
<h1>Blog Rails 3 </h1>
<% cache do %>
	<% @posts.each do |post| %> 
	<h2><%= link_to post.tittle, post %></h2> by <%= post.author.name unless post.author == nil %>	
	<div class="entry">
		<% if author_signed_in? %>
			<%= link_to "Edit", edit_post_path(post) %>
			<%= button_to "Delete", post_path(post), :confirm => "Are you sure?", :method => :delete %>
		<% end %>
		<hr/>
	</div>
	<% end %>
	<%= link_to "New Post", new_post_path %>
<% end %>

scripts/rails/blog_hacked/app/views/posts/new.html.erb
<h1>Create a new post </h1>
<%= render "form" %>

scripts/rails/blog_hacked/app/views/posts/show.html.erb
<h1><%= @post.tittle %></h1> by <%= @post.author.name unless @post.author == nil %>
<div class="entry">
	<%= @post.body %>
</div>
<h2> Comments </h2>

<%  if @post.comments.length == 0 %>
  <p>No Comments Yet :( </p>
<% else  %>
	<%= @post.comments.each do |comment| %>
		<div class="comment">
			<%=comment.body%>
		</div>
		<p>By: <%=comment.author%></p><br/>
		<%= button_to "Delete", [@post, comment], :confirm => "Are you sure ?", :metod => :delete %>
		<hr/>
	<% end %>
<% end %>

<h3> New Comment </h3>
<%= form_for [@post, Comment.new] do |form| %>
	<%= form.label :author, "Name"  %> <br/>
	<%= form.text_field :author     %> <br/>
	<%= form.text_area  :body       %> <br/>
	<%= form.submit       			%>
<% end %>

<br/>
<%= link_to "Back to Blog", posts_path %>